### ISSUE TITLE
Update WebServiceRequest class to make HttpClient a member

### ISSUE THREAD

**Issue by scottlance** [PaySimple/PaySimpleSDK#14]
Update the WebServiceRequest class to make HttpClient a static member of the class
Putting HttpClient in a using is apparently causes instability, therefore add HttpClient as a static member

Reference:

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by WillBDaniels** [comment]
This has been fixed as per https://github.com/PaySimple/PaySimpleSDK/pull/17 which is merged, closing.
