### ISSUE TITLE
Wrong CVV

### ISSUE THREAD

**Issue by onceelace** [PaySimple/PaySimpleSDK#22]
Why it is still accepting the payment even if the CVV code was invalid?

**Comment by WillBDaniels** [comment]
@onceelace payment rejection based on CVV code is handled case-by-case on the Processor's side. Now, if you're saying that there is some way to create a payment with a cvv code that is of an invalid format (aka: a non 3-digit cvv being accepted on a Visa/MasterCard/Discover, or a non 4-digit cvv on an amex), then that is certainly an issue we'll dig into. But the actual 'this cvv doesn't match this credit card' validation is handled case by case by the processor that the merchant is underwritten by.
