### ISSUE TITLE
Endpoint Error: MethodNotAllowed:

### ISSUE THREAD

**Issue by Heysoulnat88** [PaySimple/PaySimpleSDK#4]
I'm trying this PaySimple SDK and following the procedure but I'm getting an error
Endpoint Error: MethodNotAllowed:

I'm using asp.net mvc
 I have this contorller

`public async Task<ActionResult> Trial()
    {
        string username = "myusername";
        string apiKey = "apikey";
        string baseUrl = "https://sandbox-api.paysimple.com/v4/customer";
        var settings = new PaySimpleSettings( apiKey, username, baseUrl );

        var customerService = new CustomerService(settings);
        var customers = await customerService.GetCustomersAsync();

        return View(customers);
    }`

here is my view

@model IEnumerable<PaySimpleSdk.Customers.Customer>
@{
ViewBag.Title = "Index";
}

 @Html.DisplayNameFor(model => model.FirstName)
 @foreach (var item in Model)
 @Html.DisplayFor(modelItem => item.FirstName)

**Comment by WillBDaniels** [comment]
Please redirect all tech-help level inquiries to: partnersupport@paysimple.com.

**Comment by Heysoulnat88** [comment]
I asked them but they say that they don't build this PaySimpleSDK
